roles/container_status/meta/main.yml, roles/kernel_version/meta/main.yml, roles/mysql_open_files_limit/meta/main.yml, roles/system_encoding/meta/main.yml, roles/ulimits/meta/main.yml
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> Company name changed

.github/workflows/check-ansible-syntax.yml, .github/workflows/check-yaml-syntax.yml
=> github: run branch builds on main only

galaxy.yml, roles/container_status/meta/main.yml, roles/kernel_version/meta/main.yml, roles/mysql_open_files_limit/meta/main.yml, roles/system_encoding/meta/main.yml, roles/ulimits/meta/main.yml
=> ansible: add osism tag

roles/container_status/tasks/main.yml
=> Container_status: Change the place of the changed_when condition

roles/ulimits/README.rst
=> Ulimit: Add documentation for the role

roles/mysql_open_files_limit/README.rst
=> Mysql_open_files_limit: Add documentation for the role

roles/kernel_version/README.rst
=> Kernel_version: Add documentation for the role

.ansible-lint, roles/mysql_open_files_limit/tasks/main.yml
=> Cleanup Ansible-lint warnings

.gitignore, .zuul.yaml, doc/requirements.txt, doc/source/conf.py, doc/source/index.rst, tox.ini
=> Prepare repository for the role documentation

.ansible-lint, .ansible-lint-rules/osism_fqcn_list.yaml, molecule/delegated/converge.yml
Partly osism/issues#326
Signed-off-by: Ramona Beermann <rautenberg@osism.tech>
=> Fix Ansible-Lint-Errors upcoming after the last Version update

.github/workflows/test-role-container_status.yml, .github/workflows/test-role-kernel_version.yml, .github/workflows/test-role-mysql_open_files_limit.yml, .github/workflows/test-role-system_encoding.yml, .github/workflows/test-role-ulimits.yml
Signed-off-by: Christian Berendt <berendt@osism.tech>
=> github: use python 3.10 for test-role

meta/runtime.yml, roles/refstack/README.rst, roles/refstack/defaults/main.yml, roles/refstack/meta/main.yml, roles/refstack/tasks/bootstrap.yml, roles/refstack/tasks/install.yml, roles/refstack/tasks/main.yml, roles/refstack/tasks/prepare.yml, roles/refstack/templates/accounts.yaml.j2, roles/refstack/templates/prepare.sh.j2, roles/refstack/templates/run.sh.j2, roles/refstack/templates/single.sh.j2, roles/refstack/templates/tempest.conf.j2, roles/refstack/templates/test.sh.j2, roles/refstack/templates/upload.sh.j2
Initial import of contrib/refstack from osism/testbed.
Part of osism/issues#425
=> Add refstack role

.ansible-lint, galaxy.yml, roles/container_status/meta/main.yml, roles/kernel_version/meta/main.yml, roles/mysql_open_files_limit/meta/main.yml, roles/refstack/tasks/install.yml, roles/refstack/tasks/main.yml, roles/system_encoding/meta/main.yml, roles/ulimits/meta/main.yml
Use osism.validations instead of osism.services.
Close osism/issues#451
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
=> Meta: Fix wrong description

roles/container_status/meta/main.yml, roles/kernel_version/meta/main.yml, roles/mysql_open_files_limit/meta/main.yml, roles/system_encoding/meta/main.yml, roles/ulimits/meta/main.yml
Partly osism/issues#373
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
=> Meta: Add jammy to supported plattforms

roles/refstack/defaults/main.yml
=> refstack: use 2021.11 by default

roles/refstack/templates/prepare.sh.j2
=> refstack: disable test_list_show_extension test

README.md, galaxy.yml
Part of https://github.com/osism/issues/issues/927
=> Replace osism.github.io with osism.tech

.zuul.yaml, molecule/delegated/prepare/kernel_version.yml, molecule/delegated/vars/kernel_version.yml
=> zuul: test ubuntu 24.04

roles/container_status/meta/main.yml, roles/kernel_version/meta/main.yml, roles/mysql_open_files_limit/meta/main.yml, roles/refstack/meta/main.yml, roles/system_encoding/meta/main.yml, roles/ulimits/meta/main.yml
cf. https://github.com/osism/issues/issues/982
=> Update meta/main.yml files in Ansible roles

roles/tempest/README.rst, roles/tempest/defaults/main.yml, roles/tempest/meta/main.yml, roles/tempest/tasks/main.yml, roles/tempest/templates/tempest.conf.j2
Part of https://github.com/osism/issues/issues/926
=> Add tempest role

roles/prometheus_alert_status/README.rst, roles/prometheus_alert_status/defaults/main.yml, roles/prometheus_alert_status/meta/main.yml, roles/prometheus_alert_status/tasks/main.yml
Part of https://github.com/osism/issues/issues/1009
=> Add role to check prometheus for active alerts

roles/refstack/defaults/main.yml, roles/refstack/tasks/prepare.yml
This reverts commit e18836c9a8eb69652a36ce8992d6bbf006f6ca72.
=> Revert "refstack: use /share as workdir"

roles/python_version/defaults/main.yml, roles/python_version/meta/main.yml, roles/python_version/tasks/main.yml
Related: osism/issues#1133
Signed-off-by: Sven Kieske <kieske@osism.tech>
=> move the python version check from testbed

roles/ansible_version/defaults/main.yml, roles/ansible_version/meta/main.yml, roles/ansible_version/tasks/main.yml
Related: osism/issues#1133
Signed-off-by: Sven Kieske <kieske@osism.tech>
=> add ansible-core version check

roles/kernel_version/README.rst, roles/kernel_version/defaults/main.yml, roles/kernel_version/tasks/main.yml, roles/network_connectivity/tasks/main.yml
- use the ansible "version" buildin
- allow to use comparison operators
- added some documentation for the module and its parameters
- gather fact "kernel" before comparing versions
=> Improve version comparison

roles/tempest/defaults/main.yml, roles/tempest/tasks/main.yml
tempest_tag/image are already used by the kolla project.
=> tempest: fix overlapping parameter names

roles/tempest/defaults/main.yml
Revert b899fe101300ee4c4cb0b1bb1323594e6b7bfc75
Revert 07bcb25d8e5a69f72f379f5647f25d1aed208adf
=> tempest: re-enable octavia & barbican
